/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description UP */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warranties/{contractId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get warranty by contract ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    contractId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WarrantyView"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warranties/{warrantyId}/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List claims for a warranty */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    warrantyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of claims */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WarrantyClaimView"][];
                    };
                };
                /** @description Warranty not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inbound/warranty-registered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register warranty (REST fallback for warranty.coverage.registered-topic) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WarrantyRegisteredEvent"];
                };
            };
            responses: {
                /** @description Warranty registered */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inbound/defect-reported": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report defect (REST fallback for warranty.defect.reported-topic) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DefectReportedEvent"];
                };
            };
            responses: {
                /** @description Claim verified */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/warranty-registered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish warranty.coverage.registered-topic to Kafka */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event sent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/defect-reported": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish warranty.defect.reported-topic to Kafka */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event sent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seed 3 sample warranties with claims */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Seeded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/kafka-ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Smoke test Kafka connectivity */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        DefectCategory: "STRUCTURAL" | "ELECTRICAL" | "PLUMBING" | "FINISHING" | "APPLIANCE" | "OTHER";
        /** @enum {string} */
        CoverageStatus: "PENDING" | "COVERED" | "REJECTED";
        WarrantyClaimView: {
            /** Format: uuid */
            claimId?: string;
            /** Format: uuid */
            defectId?: string;
            defectCategory?: components["schemas"]["DefectCategory"];
            description?: string;
            /** Format: date-time */
            reportedAt?: string;
            coverageStatus?: components["schemas"]["CoverageStatus"];
            coverageReason?: string | null;
            /** Format: date-time */
            verifiedAt?: string | null;
        };
        WarrantyView: {
            /** Format: uuid */
            warrantyId?: string;
            /** Format: uuid */
            contractId?: string;
            /** Format: uuid */
            unitId?: string;
            /** Format: uuid */
            customerId?: string;
            /** Format: date-time */
            coverageStartsAt?: string;
            /** Format: date-time */
            coverageEndsAt?: string;
            coveredCategories?: components["schemas"]["DefectCategory"][];
            /** Format: date-time */
            registeredAt?: string;
            claims?: components["schemas"]["WarrantyClaimView"][];
        };
        WarrantyRegisteredEvent: {
            /** Format: uuid */
            contractId: string;
            /** Format: uuid */
            unitId: string;
            /** Format: uuid */
            customerId: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            coveredCategories?: components["schemas"]["DefectCategory"][];
        };
        DefectReportedEvent: {
            /** Format: uuid */
            defectId: string;
            /** Format: uuid */
            contractId: string;
            /** Format: uuid */
            unitId: string;
            /** Format: uuid */
            customerId: string;
            defectCategory: components["schemas"]["DefectCategory"];
            description?: string;
            /** Format: date-time */
            reportedAt?: string;
        };
        ErrorResponse: {
            error?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
